<a href="https://colab.research.google.com/github/asteriaji/MSSP6070/blob/main/Assignments/Week%204/Jiangyu_Ji_Assignment_PARTICIPATION_ACTIVITY_Week_4_Opening_a_CSV_file_and_modifying_the_contents__(3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
import csv

with open('/content/drive/MyDrive/MSSP 6070/a.  Assignments/Week 4/parsed.csv', encoding='UTF-8') as f:
    reader = csv.reader(f)
    data = list(reader)

In [8]:
data[0]

['alert',
 'cdi',
 'code',
 'detail',
 'dmin',
 'felt',
 'gap',
 'ids',
 'mag',
 'magType',
 'mmi',
 'net',
 'nst',
 'place',
 'rms',
 'sig',
 'sources',
 'status',
 'time',
 'title',
 'tsunami',
 'type',
 'types',
 'tz',
 'updated',
 'url',
 'parsed_place']

In [9]:
# 2.a.
import pandas as pd
df = pd.DataFrame(data[1:], columns=data[0])
df.info()
percentile_95 = df[(df['parsed_place'] == 'Japan') & (df['magType'] == 'mb')]['mag'].astype(float).quantile(0.95)
print('The 95th percentile of earthquake magnitude in Japan for earthquakes with a magnitude type of mb is',percentile_95)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9332 entries, 0 to 9331
Data columns (total 27 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   alert         9332 non-null   object
 1   cdi           9332 non-null   object
 2   code          9332 non-null   object
 3   detail        9332 non-null   object
 4   dmin          9332 non-null   object
 5   felt          9332 non-null   object
 6   gap           9332 non-null   object
 7   ids           9332 non-null   object
 8   mag           9332 non-null   object
 9   magType       9332 non-null   object
 10  mmi           9332 non-null   object
 11  net           9332 non-null   object
 12  nst           9332 non-null   object
 13  place         9332 non-null   object
 14  rms           9332 non-null   object
 15  sig           9332 non-null   object
 16  sources       9332 non-null   object
 17  status        9332 non-null   object
 18  time          9332 non-null   object
 19  title         9332 non-null   object
 20  tsunami       9332 non-null   object
 21  type          9332 non-null   object
 22  types         9332 non-null   object
 23  tz            9332 non-null   object
 24  updated       9332 non-null   object
 25  url           9332 non-null   object
 26  parsed_place  9332 non-null   object
dtypes: object(27)
memory usage: 1.9+ MB
The 95th percentile of earthquake magnitude in Japan for earthquakes with a magnitude type of mb is 4.9

In [10]:
# 2.b.
indonesia_number = df[df['parsed_place'] == 'Indonesia']
percentage = indonesia_number['tsunami'].value_counts()['1'] / len(indonesia_number) * 100
print('The percentage of earthquakes in Indonesia that were coupled with tsunamis is', percentage)

The percentage of earthquakes in Indonesia that were coupled with tsunamis is 23.12925170068027

In [11]:
# 2.c.
df[df['parsed_place'] == 'Nevada'].describe()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,status,time,title,tsunami,type,types,tz,updated,url,parsed_place
count,681,681,681,681,681,681,681,681,681,681,...,681,681,681,681,681,681,681,681,681,681
unique,1,6,681,681,318,5,669,681,39,2,...,2,681,630,1,3,7,1,681,681,1
top,,,00657031,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.035,,93.22,",nn00657031,",0.1,ml,...,reviewed,1537247268525,"M -0.3 - 55km ENE of Beatty, Nevada",0,earthquake,",geoserve,origin,phase-data,",-480.0,1537322665893,https://earthquake.usgs.gov/earthquakes/eventp...,Nevada
freq,681,666,1,1,9,666,2,1,57,680,...,675,1,4,681,647,651,681,1,1,681

In [15]:
# 2.d.
df['ring_of_fire'] = df['parsed_place'].str.contains(
    r'|'.join([
        'Bolivia', 'Chile', 'Ecuador', 'Peru', 'Costa Rica',
        'Guatemala', '^Mexico', 'Japan', 'Philippines', 'Indonesia',
        'New Zealand', 'Antarctic', 'Canada', 'Fiji',
        'Alaska', 'Washington', 'California', 'Russia',
        'Taiwan', 'Tonga', 'Kermadec Islands']),
    regex=True,
    na=False)
df

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,time,title,tsunami,type,types,tz,updated,url,parsed_place,ring_of_fire
0,,,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693000000000001,,85.0,",ci37389218,",1.35,ml,...,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
1,,,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030000000000003,,79.0,",ci37389202,",1.29,ml,...,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
2,,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.02137,28.0,21.0,",ci37389194,",3.42,ml,...,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
3,,,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180000000000002,,39.0,",ci37389186,",0.44,ml,...,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
4,,,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.07799,,192.0,",nc73096941,",2.16,md,...,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9327,,,73086771,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01806,,185.0,",nc73086771,",0.62,md,...,1537230228060,"M 0.6 - 9km ENE of Mammoth Lakes, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1537285598315,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
9328,,,38063967,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.030410000000000003,,50.0,",ci38063967,",1.0,ml,...,1537230135130,"M 1.0 - 3km W of Julian, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1537276800970,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
9329,,,2018261000,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.4526,,276.0,",pr2018261000,",2.4,md,...,1537229908180,"M 2.4 - 35km NNE of Hatillo, Puerto Rico",0,earthquake,",geoserve,origin,phase-data,",-240.0,1537243777410,https://earthquake.usgs.gov/earthquakes/eventp...,Puerto Rico,False
9330,,,38063959,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01865,,61.0,",ci38063959,",1.1,ml,...,1537229545350,"M 1.1 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537230211640,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
9331,,,38063935,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.016980000000000002,,39.0,",ci38063935,",0.66,ml,...,1537228864470,"M 0.7 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537305830770,https://earthquake.usgs.gov/earthquakes/eventp...,California,True

In [16]:
# 2.e.
in_ring_of_fire_number = df[
    (df['ring_of_fire'] == True) &
    (df['type'] == 'earthquake')
]

print('The number of earthquakes in the Ring of Fire locations is', len(in_ring_of_fire_number))

not_in_ring_of_fire_number = df[
    (df['ring_of_fire'] == False) &
    (df['type'] == 'earthquake')
]

print('The number of earthquakes in the Ring of Fire locations is', len(not_in_ring_of_fire_number))

The number of earthquakes in the Ring of Fire locations is 7004
The number of earthquakes in the Ring of Fire locations is 2077

In [17]:
# 2.f.
tsunami_ring_of_fire = df[(df['ring_of_fire'] == True) & (df['tsunami'] == '1')]
print(len(tsunami_ring_of_fire))

45