<a href="https://colab.research.google.com/github/asteriaji/MSSP6070/blob/main/Assignments/Week%204/Jiangyu_Ji_Assignment_PARTICIPATION_ACTIVITY_Week_4_Opening_a_CSV_file_and_modifying_the_contents__260920(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/MSSP 6070/a.  Assignments/Week 4/parsed.csv')

In [6]:
# 2.a.
df.info()
percentile_95 = df[(df['parsed_place'] == 'Japan') & (df['magType'] == 'mb')]['mag'].astype(float).quantile(0.95)
print('The 95th percentile of earthquake magnitude in Japan for earthquakes with a magnitude type of mb is',percentile_95)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9332 entries, 0 to 9331
Data columns (total 27 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   alert         59 non-null     object
 1   cdi           329 non-null    float64
 2   code          9332 non-null   object
 3   detail        9332 non-null   object
 4   dmin          6139 non-null   float64
 5   felt          329 non-null    float64
 6   gap           6164 non-null   float64
 7   ids           9332 non-null   object
 8   mag           9331 non-null   float64
 9   magType       9331 non-null   object
 10  mmi           93 non-null     float64
 11  net           9332 non-null   object
 12  nst           5364 non-null   float64
 13  place         9332 non-null   object
 14  rms           9332 non-null   float64
 15  sig           9332 non-null   int64
 16  sources       9332 non-null   object
 17  status        9332 non-null   object
 18  time          9332 non-null   int64
 19  title         9332 non-null   object
 20  tsunami       9332 non-null   int64
 21  type          9332 non-null   object
 22  types         9332 non-null   object
 23  tz            9331 non-null   float64
 24  updated       9332 non-null   int64
 25  url           9332 non-null   object
 26  parsed_place  9332 non-null   object
dtypes: float64(9), int64(4), object(14)
memory usage: 1.9+ MB
The 95th percentile of earthquake magnitude in Japan for earthquakes with a magnitude type of mb is 4.9

In [8]:
# 2.b.
indonesia_number = df[df['parsed_place'] == 'Indonesia']
percentage = indonesia_number['tsunami'].value_counts()[1] / len(indonesia_number) * 100
print('The percentage of earthquakes in Indonesia that were coupled with tsunamis is', percentage)

The percentage of earthquakes in Indonesia that were coupled with tsunamis is 23.12925170068027

In [12]:
# 2.c.
Nevada = df[df['place'].str.contains('Nevada', na=False)]
Nevada.describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.000000,677.000000,15.000000,677.000000,677.000000,1.00,677.000000,677.000000,677.000000,6.770000e+02,677.0,677.0,6.770000e+02
mean,2.440000,0.166982,2.400000,154.029527,0.491728,2.84,12.608567,0.151909,10.688331,1.538314e+12,0.0,-480.0,1.538402e+12
std,0.501142,0.166400,4.626013,68.769713,0.689560,NaN,9.890620,0.084742,19.252727,5.954070e+08,0.0,0.0,6.000267e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537307e+12
25%,2.000000,0.054000,1.000000,97.670000,-0.100000,2.84,6.000000,0.106900,0.000000,1.537854e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.113000,1.000000,149.550000,0.400000,2.84,9.000000,0.146300,2.000000,1.538280e+12,0.0,-480.0,1.538428e+12
75%,2.900000,0.234000,1.000000,200.470000,0.900000,2.84,16.000000,0.186700,12.000000,1.538821e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.863400,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

In [14]:
# 2.d.
df['ring_of_fire'] = df['parsed_place'].str.contains(
    r'|'.join([
        'Bolivia', 'Chile', 'Ecuador', 'Peru', 'Costa Rica',
        'Guatemala', '^Mexico', 'Japan', 'Philippines', 'Indonesia',
        'New Zealand', 'Antarctic', 'Canada', 'Fiji',
        'Alaska', 'Washington', 'California', 'Russia',
        'Taiwan', 'Tonga', 'Kermadec Islands']),
    regex=True,
    na=False)
df

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,time,title,tsunami,type,types,tz,updated,url,parsed_place,ring_of_fire
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9327,NaN,NaN,73086771,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.018060,NaN,185.0,",nc73086771,",0.62,md,...,1537230228060,"M 0.6 - 9km ENE of Mammoth Lakes, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1537285598315,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
9328,NaN,NaN,38063967,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.030410,NaN,50.0,",ci38063967,",1.00,ml,...,1537230135130,"M 1.0 - 3km W of Julian, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1537276800970,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
9329,NaN,NaN,2018261000,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.452600,NaN,276.0,",pr2018261000,",2.40,md,...,1537229908180,"M 2.4 - 35km NNE of Hatillo, Puerto Rico",0,earthquake,",geoserve,origin,phase-data,",-240.0,1537243777410,https://earthquake.usgs.gov/earthquakes/eventp...,Puerto Rico,False
9330,NaN,NaN,38063959,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.018650,NaN,61.0,",ci38063959,",1.10,ml,...,1537229545350,"M 1.1 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537230211640,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
9331,NaN,NaN,38063935,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.016980,NaN,39.0,",ci38063935,",0.66,ml,...,1537228864470,"M 0.7 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537305830770,https://earthquake.usgs.gov/earthquakes/eventp...,California,True

In [15]:
# 2.e.
in_ring_of_fire_number = df[
    (df['ring_of_fire'] == True) &
    (df['type'] == 'earthquake')
]

print('The number of earthquakes in the Ring of Fire locations is', len(in_ring_of_fire_number))

not_in_ring_of_fire_number = df[
    (df['ring_of_fire'] == False) &
    (df['type'] == 'earthquake')
]

print('The number of earthquakes in the Ring of Fire locations is', len(not_in_ring_of_fire_number))

The number of earthquakes in the Ring of Fire locations is 7004
The number of earthquakes in the Ring of Fire locations is 2077

In [16]:
# 2.f.
tsunami_ring_of_fire = df[(df['ring_of_fire'] == True) & (df['tsunami'] == 1)]
print(len(tsunami_ring_of_fire))

45